---
# Fix: '''Fetch and check assertions for snap "core22" (1612) (persistent network error'''

- name: Restart snapd
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: snapd
  become: true

- name: Create fix_log directory
  ansible.builtin.file:
    path: "{{ fix_log_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true

- name: ping api.snapcraft.io
  ansible.builtin.shell: |
    ping api.snapcraft.io -c 5
    touch {{ fix_log_dir }}/persistent_network_error
  args:
    creates: "{{ fix_log_dir }}/persistent_network_error"